### ISSUE TITLE
Available/reserverd features?

### ISSUE THREAD

**Issue by esaheiskanen** [uStepper/uStepperS#13]
Hi!

Which 328pb featuers are reserved for ustepper s? I just noteced that serial1 (pins 5&6) interfere with stepperdriver. Is there a way top make serial1 to work?

**Comment by uStepper** [comment]
Hi Esa,

The Serial1 feature is not reserved on either the uStepper S or S Lite, and does not interfere with the stepper driver. I am using the Serial1 in some of my sketches to get data from a wifi module (without any hardware/software modification)

On the uStepper S, SPI1 is used for the stepper driver, so this peripheral is not available to the user. The schematics are available under the hardware folder in this repository, if you want to take a closer look on which peripherals and pins are available on the pin headers

Best Regards,
Thomas Olsen
