### ISSUE TITLE
moveAngle v moveToAngle

### ISSUE THREAD

**Issue by thehelpless** [uStepper/uStepperS#18]
Hi,

In the class list for the uStepper S there is both moveAngle and moveToAngle.
The descriptions for the two are identical, however the code is not.

Am i right that moveAngle is relative while moveToAngle is absolute based on the initiation of PID and using setHome?

Thanks

**Comment by uStepper** [comment]
Hi,

That is not intended that the documentation is identical.

But yes, you are absolutely correct

Best Regards,
Thomas Olsen

**Comment by uStepper** [comment]
Corrected the description in the develop branch

Best regards,
Mogens
