### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ghulands** [uStepper/uStepperS#2]
The readme says to follow the original documentation which talks about the ftdichip vcp. uStepper S uses the Silicon Labs VCP. It might save someone else 10 minutes why the port doesn't show up in the Arduino environment. ;-)

**Comment by uStepper** [comment]
Thank you for noticing !
I will have the readme updated soon. are you using a mac?
Best Regards,
Thomas Olsen

**Comment by ghulands** [comment]
Yes, using macOS.

**Comment by sfandersen** [comment]
I am using Windows 10. It the uStepperS did not show up as a serial port before I downloaded this driver: https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by uStepper** [comment]
Thanks for pointing out that this issue can also occur on windows 10 !
