### ISSUE TITLE
Permission denied in objcopy crtatmega328pb.o

### ISSUE THREAD

**Issue by HermanEldering** [uStepper/uStepperS#21]
I am using the Windows Store version of Arduino. When using the uStepperS board I get a permission denied error when it attempts to copy the crtatmega328pb file.

From this forum post it also appears to happen when the Arduino IDE is installed inside the program files folder: https://forum.arduino.cc/index.php?topic=638028.0

For now I've seemed to fix it by commenting out the lines below in the file "packages\uStepper\hardware\avr\2.2.0\platform.txt". I'm not sure if this will cause problems somewhere else but with these changes the bounce example compiles and runs on the board.

```
# Copy the startup and c runtime libs to the right folder / thx to elector  
#recipe.hooks.linking.prelink.1.pattern="{compiler.path}{compiler.objcopy.cmd}" "{runtime.platform.path}/tools/lib/crtatmega328pb.o" "{runtime.tools.avr-gcc.path}/avr/lib/avr5/crtatmega328pb.o"
#recipe.hooks.linking.prelink.2.pattern="{compiler.path}{compiler.objcopy.cmd}" "{runtime.platform.path}/tools/lib/crtatmega328pb.o" "{runtime.tools.avr-gcc.path}/avr/lib/avr5/crtm328pb.o"
#recipe.hooks.linking.prelink.3.pattern="{compiler.path}{compiler.objcopy.cmd}" "{runtime.platform.path}/tools/lib/libatmega328pb.a" "{runtime.tools.avr-gcc.path}/avr/lib/avr5/libatmega328pb.a"
```

**Comment by uStepper** [comment]
Hi Herman,

That issue is related to the windows store version of Arduino IDE, which currently have issue with some functions and boards. we recommend that you use the version downloaded directly from arduino.cc.

Best Regards,
Thomas Olsen
