### ISSUE TITLE
ShaftOrientiation is not correctly maintained

### ISSUE THREAD

**Issue by Nestilaos** [uStepper/uStepperS#23]
Shaft orientation is set in the GCONF register of the driver and correctly set in the corresponding function inside uStepperDriver.cpp.

Unfortunately, the bit is not respected and set to zero, as soon as 
- uStepperDriver::enableStealth()
- uStepperDriver::enableStallguard( int8_t threshold, bool stopOnStall )
- uStepperDriver::disableStallguard( void )
are called.

Therefore, in most of my scenarios the result of uStepperS::checkOrientation was not respected.

Best regards.

**Comment by uStepper** [comment]
Hi - good catch :) We were already working on it and I have just pushed the corrected to the develop branch. When tested by a second party in our group we will merge into master and make a release with the fix.
