### ISSUE TITLE
[FR] Support for Marlin 2.0.X Closed-loop controller function?

### ISSUE THREAD

**Issue by felixekman** [uStepper/uStepperS#24]
Are there any plans to expand support for Drop-in/replacement to be compatible with the new Marlin Firmware closed-loop controller functions? At a glance, it does not seem to be too difficult as it only requires the addition of two pins/variables:

#EXTERNAL_CLOSED_LOOP_CONTROLLER

CLOSED_LOOP_ENABLE_PIN        -1
CLOSED_LOOP_MOVE_COMPLETE_PIN -1

**Comment by uStepper** [comment]
Support for the Marlin closed-loop firmware will not be implemented but it should be possible to do this by adding some functionality to our closedloop sketch for those two required I/O's
