### ISSUE TITLE
example on how to use the other pins?

### ISSUE THREAD

**Issue by RobertoPuglieseFusco** [uStepper/uStepperS#25]
where can I find an example on how to use the other available pins?
for instance use PWM enabled pin to dim a light.
Thanks!

**Comment by uStepper** [comment]
Hi Roberto,

This is done the same way as any other Arduino Board. 
For general input/output pin usage check this guide:
https://www.allaboutcircuits.com/projects/learn-how-to-use-the-arduinos-digital-i-o/

for PWM, check out the following:
https://create.arduino.cc/projecthub/muhammad-aqib/arduino-pwm-tutorial-ae9d71

Best Regards,
Thomas Olsen
