### ISSUE TITLE
[feature requests] hardware reset and interrupt lines

### ISSUE THREAD

**Issue by greyltc** [uStepper/uStepperS#29]
I wonder if in the next hardware revision you make you could tie pin 10 on the TMC driver (VCC_IO) to a pin on the microcontroller (or at least allow it to pull that line down momentarily).

This would allow the microcontroller to properly reset the driver IC. I'm not sure if there's an easy way in the current design to get all the driver's registers into a known state (is there?).

Also, would be great to have SWN_DIAG0 (pin 26) and SWP_DIAG1 (pin 27) from the stepper driver on interrupt enabled pins of the microcontroller!

**Comment by uStepper** [comment]
Hi,

uStepper S will not receive further updates to hardware, and only limited updates to software.

however, we will take it into our considerations for our newest product, uStepper S32.

Best Regards
uStepper Team
