### ISSUE TITLE
The max velocity seems wrong

### ISSUE THREAD

**Issue by sfandersen** [uStepper/uStepperS#3]
I think the max value that can be set is for VMAX should be 0x7FFE00

See the driver documentation: 
![image](https://user-images.githubusercontent.com/12411130/53040546-f063ab00-3481-11e9-8f50-0b282d0d2f4d.png)

I think the code should be: 
	if( abs(velocity * this->microSteps) > (float)(0x7FFE00)) {
		velocity = (float)0x7FFE00 / this->microSteps;
	}

See:
https://github.com/uStepper/uStepperS/blob/2ae15273d868393d964261376dd657c965204c8a/src/uStepperS.cpp#L291

**Comment by uStepper** [comment]
You are correct, this will be updated in next release !

**Comment by sfandersen** [comment]
I would suggest only closing the bugs that are fixed.
