### ISSUE TITLE
VCP driver for Windows 10

### ISSUE THREAD

**Issue by ghulands** [uStepper/uStepperS#30]
Hi,
I'm trying to help my friend set up the uStepper S environment on Windows 10, but when I plug in the usb on it, Windows 10 is not creating a virtual com port.

Which Virtual COM port driver do i need to install for the devices to appear in the Aurdino IDE?

Thanks,
Greg

**Comment by uStepper** [comment]
Hi Greg,

You should install the following VCP driver:
https://www.silabs.com/documents/public/software/CP210x_Windows_Drivers.zip

Best regards,
Thomas Olsen
