### ISSUE TITLE
Spurious change to DDRB port in uStepperS::setup

### ISSUE THREAD

**Issue by thekeeno** [uStepper/uStepperS#33]
In line 269 of uStepperS.cpp, we have:

`/DDRB |= (1 << 4);`

 It sets the data direction on pin 4 of port B as output. This is the MISO0/RXD1 pin, which is not used by the driver or the encoder and should, in principle, be user configurable. 

This line seems spurious and actually interferes with some other libraries when used on the uStepperS. The line in question does not seem to serve any purpose to the uStepper - so I suggest it be removed.

**Comment by uStepperOld** [comment]
Fixed in release 2.3.2
