### ISSUE TITLE
Analog pins A0 and A2 labels are exchanged (A0 should be A2 and vice versa)

### ISSUE THREAD

**Issue by LibrEars** [uStepper/uStepperS#35]
Hi,

on my board I noticed that the analog pins A0 and A2 are exchanged (A0 should be A2 and vice versa). The labels in the product sheet are wrong (also in the schematics) and on the bord. The serial ports SCL0 and SCL1 are labeled right on the other hand.

Maybe this has something to do with the upgrade from ATmega328P to ATmega328P**B**?

**Comment by uStepper** [comment]
fixed in release 2.2.4
