### ISSUE TITLE
Motor starts moving after 'setMaxVelocity' is set.

### ISSUE THREAD

**Issue by Daniel-Walther** [uStepper/uStepperS#36]
**Bug at 2.2.1 version:**

After stopping the moter by 'uStepperS.stop(HARD)' or 'uStepperS.stop(SOFT)' the motor starts immediately runing at the next 'uStepperS.setMaxVelocity(XXX)' command.

**Example:**

```cpp
#include <uStepperS.h>
uStepperS stepper;
void setup()
{  
	stepper.setup();
	stepper.checkOrientation(30.0);
	MoveHome(false);
	stepper.stop(SOFT);
	stepper.setMaxVelocity(1000); //-->here motor starts to move
}
```

**Attempt to explain:**
The 'stop' method at the uStepperS code only sets the target speed to zero. But the target-position register is not set. Then changing the velocity to a none-zero value the driver starts to moving to the value which is set to the target position register.

**Workaraound:**
The 'stop' method at the uStepperS code should wait until the motor realy stops movement. After that, the target position should set to the current position:

**ORIGINAL CODE:**
```cpp
void uStepperS::stop( bool mode){
	if(mode == HARD)
	{
		this->driver.setDeceleration( 0xFFFE );
		this->driver.setAcceleration( 0xFFFE );
		this->setRPM(0);
		while(this->driver.readRegister(VACTUAL) != 0);
		this->driver.setDeceleration( (uint32_t)( this->maxDeceleration ) );
		this->driver.setAcceleration( (uint32_t)(this->maxAcceleration ) );
	}
	else
	{
		this->setRPM(0);
	}
}
```

**WORKAROUND CODE:**
```cpp
void uStepperS::stop( bool mode){
	if(mode == HARD)
	{
		this->driver.setDeceleration( 0xFFFE );
		this->driver.setAcceleration( 0xFFFE );
		this->setRPM(0);
		while(this->driver.readRegister(VACTUAL) != 0);
		this->driver.setDeceleration( (uint32_t)( this->maxDeceleration ) );
		this->driver.setAcceleration( (uint32_t)(this->maxAcceleration ) );
	}
	else
	{
		this->setRPM(0);
		while(this->driver.readRegister(VACTUAL) != 0);
	}
	// Get current position
	int32_t current = this->driver.getPosition();
	// Set new position
	this->driver.setPosition( current );
}
```

**Comment by uStepper** [comment]
Change implemented in latest release
