### ISSUE TITLE
USB Communication with HOST PC

### ISSUE THREAD

**Issue by andybee909** [uStepper/uStepperS#37]
Hi! I am using uStepperS instead of an Arduino Uno + PWM Motor. The uStepperS should
receive informations via USB 115.200 Baud. When I start the communication between uStepper and PC Software,
it does a reset on the uStepper. With Arduino Uno, everything works fine. Is for the ustepper another commonication library needed?
As far as I noticed, the uStepperS uses mostly the same CPU as Arduino Uno? (Atmega328)
Pins D0 and D1 are not in use because of RX0/TX0 (USB).
I also have noticed, the uStepper uses a Atmega328PB, which is a bit different...
Thanks for your support! Have a nice sunday evening ;)

**Comment by uStepper** [comment]
It is only on port opening the MCU will reset which is caused by the intentional hardware solution made around the USB chip.
