### ISSUE TITLE
Overflow bug in stepper setup

### ISSUE THREAD

**Issue by matt-phair** [uStepper/uStepperS#4]
in `uStepperS::setup`, there is the line:

```
this->angleToStep = (float)(this->fullSteps*this->microSteps)/360.0;
```

by default, `microSteps` is `256` so if we call `setup` with `stepsPerRevolution` equal to anything over 256, the above will overflow.

This is a problem for (as an example) this motor: https://www.omc-stepperonline.com/nema-17-bipolar-09deg-46ncm-651ozin-2a-28v-42x42x48mm-4-wires-17hm19-2004s.html which has 400 steps per revolution.

The code could be corrected to be something like:

```
this->angleToStep = (float)this->fullSteps * (float)this->microSteps / 360.0
```

**Comment by uStepper** [comment]
corrected for the upcoming version . Thanks for the input !
