### ISSUE TITLE
Platform support for vs code platform io 

### ISSUE THREAD

**Issue by smukkejohan** [uStepper/uStepperS#43]
Has there been any work adding support for the ustepper through vscode with platform io. 

I know lots of people are using that as their preferred IDE in favor of the rather minimal arduino IDE. 

Happy to help look into it, maybe someone is already on to it?

**Comment by smukkejohan** [comment]
Opened a request here: https://github.com/platformio/platformio-core/issues/4387

**Comment by uStepper** [comment]
Hi Johan,

We have not been looking into adding support for platform io. 

If you are willing to look into it, it would be much appreciated ! :)
