### ISSUE TITLE
Reading encoder data

### ISSUE THREAD

**Issue by GabrielGms** [uStepper/uStepperS#9]
Hello, i'm working on my research and this board is exactly what i need, but i have a specific need, read the data used in PID controller on another board. I don't need write data, only read to control a second code, running in another microcontroller, using the output error, this is possible? how?

**Comment by uStepper** [comment]
Hi,
That would require alteration of the library. It can be done, but it require some coding from you.

Best regards, Mogens

**Comment by uStepper** [comment]
Closing issue due to long inactivity
